### ISSUE TITLE
TextArea in Chrome has 2px more than in other browsers

### ISSUE THREAD

**Issue by SharpNoiZy** [necolas/normalize.css#126]
Can you maybe somehow normalize/fix this.
This is realy bad.

``` html
<input type="text" style="width: 200px">
<textarea style="width: 200px"></textarea>
```

Looks great in IE, both boxes have the same length, but in Google Chrome the textarea has 2px more width ;(

Best regards

**Comment by MetalG3arSo1id** [comment]
I found the problem in chrome was the wrapper container height was an ODD height value e.g. 401px all borders looked to be 2px. Every time the container height was e.g. 400px all borders within it changed to 1px. This is great news for static content, just style the wrapper container to be of a even height value. But for dynamic content in wrapper containers this sucks, because there is no way of making sure the wrapper height value will be an even or odd number.

**Comment by MetalG3arSo1id** [comment]
Generic solution found on https://css-tricks.com/forums/topic/make-a-div-height-always-round-to-an-even-number/
