### ISSUE TITLE
Remove rounded corners on input elements in Mobile WebKit

### ISSUE THREAD

**Issue by iamkeir** [necolas/normalize.css#178]
Spotted that Mobile WebKit gives input elements a border-radius - would the removal of this be within normalize's remit?

http://jsfiddle.net/iamkeir/FnN5u/

![IMG_4630](https://f.cloud.github.com/assets/539615/336274/d2417260-9ca2-11e2-8372-a2b2c2d6f901.PNG)
![iOS Simulator Screen shot 3 Apr 2013 22 03 47](https://f.cloud.github.com/assets/539615/336273/d228edc6-9ca2-11e2-90db-0c7bbf572407.png)

**Comment by somsekhar** [comment]
The below css works for me.

input {
            -webkit-border-radius: 0;
            border-radius: 0;
            -webkit-box-shadow: none;
            box-shadow: none;
        }

**Comment by garrettw** [comment]
That code was already suggested and rejected for the above-stated reasons.

**Comment by adamwathan** [comment]
>  input buttons lose a lot of styles

Curious if anyone knows the specifics of what @necolas was talking about here, or knows of any other issues besides the radio buttons losing their border radius?

Considering a simple reset like this in one of my own projects and trying to figure out if there are unintended consequences I need to worry about:

```css
input,
button,
select,
textarea {
  border-radius: 0;
}

[type="radio"] {
  border-radius: 50%;
}
```

**Comment by gouch** [comment]
What @necolas was getting at, I think, is that controlling form element appearance is an all-or-nothing project. You can set some color and font properties and be okay, but if you start touching style/layout now you’ve signed up for a lot of work — with risk. (Think  borderless white checkboxes on a white page (i.e. invisible) in the one browser+OS combo you didn’t check.)

You have to look at each form element in each browser on each OS, because those elements inherit/mimic styles from the OS. You get that for free, but if you mess around, at some point the browser will toggle off its attempt and let you have at it. (I think this is because something like a radio isn’t just a styled up `div` but is a widget coming from the OS.) That means you have to re-specify every property from scratch and then do a thorough browser check.

For example, the code above that’s supposed to just change the `border-radius` causes Mac Firefox to drop additional parts of its default styling, so now I have to re-specify the borders I want. Maybe I *would/should* be doing that anyway, but that's why form element styling is all-or-nothing.

![just-normalize](https://user-images.githubusercontent.com/38445/54294121-7063c900-4587-11e9-95b7-c707ad81be23.png)
![normalize-with-border-radius](https://user-images.githubusercontent.com/38445/54294131-735eb980-4587-11e9-9d0c-ec8491a5afda.png)

Also, I would say never apply CSS to the bare `input` element — those aren’t just text: they are buttons, sliders, date pickers, and more. There’s only like seven “text-like” inputs, so I always specify those directly (e.g. `input[type="email"], input[type="number"], …, textarea`)

**Comment by garrettw** [comment]
[offtopic] for less specificity and CPU cycles I usually don't target the element name unless I need to -- so just `[type="submit"]`, `[type="text"]`, etc. [/offtopic]
