### ISSUE TITLE
Break into parts

### ISSUE THREAD

**Issue by necolas** [necolas/normalize.css#222]
Might be worth building the normalize.css file from several parts. Perhaps web components would want to import the section of styles their component needs normalized as a base.

**Comment by electricessence** [comment]
https://github.com/electricessence/normalize.less
Broken into LeSS partial files (prefixed with _ and rendered via gulp).
I then added extended partials for forms.

**Comment by electricessence** [comment]
It's very nice to have in separate files because then each partial can be tracked individually.

**Comment by thezoggy** [comment]
I see little gain in breaking it apart... It's not that big and changes are usually minor/few lines.. This git history works fine...

-----Original Message-----

**Comment by electricessence** [comment]
@thezoggy, I think that's a matter of preference mostly.  Personally, I think it allows for a better starting point for evolving it.  Pull requests become more isolated and there's less worry about if a particular category has been polluted.

**Comment by eltonmesquita** [comment]
If this is to ever happen, I think that an [approach similar to the current animate.css build system](https://github.com/daneden/animate.css) would be the best option. It doesn't use any pre-processor, just separated css files that are concatenated according to the config.json file.

Grunt makes this possible and pretty straight forward.

**Comment by LukeAskew** [comment]
:+1:  for adopting a pre-processor, specifically Sass.

Using Sass not only gets you the partials, it would allow us to directly configure a normalized stylesheet through default variable overrides (isn't that).

Something like this: http://sassmeister.com/gist/4746464753189c9ab393

This would help fulfill the project's description of a "customizable CSS file".

**Comment by electricessence** [comment]
@LukeAskew after toying with both SASS and LESS, I have to pick less for it's greater flexibility.  Not that you couldn't use sass to do this, but I can also easily run gulp-less-to-scss if you still want .scss versions.
"What can LESS do that SASS can't?" You might ask?  We'll there's quite a bit actually.  LESS can take closures and can also concatenate class names in ways that SASS can't.
If you disagree, then look here (https://github.com/electricessence/css-helpers/blob/master/table-cells.less) and tell me how you would make this work the same in SASS without adding more code or redundancy.  But let's not make this thread a SASS versus LESS debate.  They both work.  And if you want a .scss version, let me know.

**Comment by tbremer** [comment]
holy unqualified selectors batman.

**Comment by anEffingChamp** [comment]
How will this affect a user who just wants an agnostic CSS file?

**Comment by eltonmesquita** [comment]
@anEffingChamp That's why I'm suggesting a simple pure CSS build system. I don't think that a pre-processor will help normalize.css in any way. It'll only make it look more biased to a certain workflow. I think normalize should be as universal as possible, as this is its objective any way, so nothing better than pure CSS, right?

**Comment by anEffingChamp** [comment]
Precisely, a CSS reset is not the place to start introducing biases to a project.

**Comment by digitalcrusade** [comment]
@eltonmesquita @anEffingChamp agree with the both of you.

**Comment by electricessence** [comment]
Hmmmm... I would totally concede that it should be pure CSS and you could simply use a build step that combines the parts.  But it seems silly if you are going to break it apart to then miss out on what pre-processors already do (combine CSS).

**Comment by jonathantneal** [comment]
I recommend separating normalize.css into two major sections: **normalizations** and **expectations**.

The normalizations section would strictly include declarations that provide missing or inconsistent styling between browsers. Here you would find most display definitions and text-level semantics.

I recommend that each rule or declaration specifically list the browser(s) and version(s) affected. This will be helpful to contributors, cross-browser testers, and every-day developers alike.

The expectations section would strictly include declarations that provide common or useful patterns in modern web developer. For example, normalize.css includes alternative text alignment for sub and sup elements because the universal defaults do not meet most designers’ line-height flow expectations. As another example, the border on images within an anchor is an obscure gotcha unique to this one kind of media. Other expectation examples include the baseline font family as sans-serif, the zero’d table border and spacing, and the hr element styles. While many developers greatly appreciate these changes, they are not true normalizations.

I also recommend that all expectations be made configurable. This would require a more serious change since native CSS yet provides this level of configuration.

[Sass Variables](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#variable_defaults_) could be used to define all the opinionated defaults at the top of the file. These values could be easily overridden inside or outside normalize.scss if the `!default` syntax were used.

```scss
$small-font-size: 80% !default; // used only if $small-font-size is not already specified

small {
  font-size: $small-font-size;
}
```

In the above example, the compiled normalize.css would remain the same, as these configurations would become hard-coded. You have objected to pre-compilers in the past, but I’m not sure if you have considered this use case.

**Comment by jonathantneal** [comment]
With tools like PostCSS, we don’t need to break this apart for someone to extract specific rules for whatever reason. And to respond to my earlier comment, all expectations in normalize.css are now labeled as opinionated defaults. Overriding opinionated defaults in normalize.css is trivial and doesn’t really necessitate adding something like a sass version, or a version with css variables.

After 2.5 years of no further input from Nicolas, I’m closing this.
