### ISSUE TITLE
Problem with pre overflow auto.

### ISSUE THREAD

**Issue by OpenSiteMobile** [necolas/normalize.css#313]
Hi,

Not a big problem, but I had to remove the pre { overflow: auto: } specification from my v3.0.0 normalize.css so that my pre tags within a div { overflow: auto; } would scroll properly. The problem seems to be that at least in Chrome (Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/32.0.1700.107 Chrome/32.0.1700.107 Safari/537.36), you can't undo the overflow: auto; with some other setting. The pre element scrolls horizontally first.

To be specific, I want white-space: pre, and not white-space: pre-wrap; So this is more of a heads-up, than a real issue. Many users might not care too much. Not sure, but by a quick search of past issues, this might be something that may be better set per installation. It seems to be quite fluid as to what is the best "default" value for each application. Just a thought.

**Comment by jonathantneal** [comment]
`pre { overflow: auto; }` is an opinionated default that prevents undesirable horizontal scrolling on a page with long contents in a `<pre>`.

*Aside: I added this in [the first commit to normalize.css](https://github.com/necolas/normalize.css/blob/d8335d302adef6fe2632925167c358ef1c7c6145/normalize.css#L110-L119). (Technically [this was the first commit](https://github.com/necolas/normalize.css/commit/0434c40f4dd704cf4c5df1825905e2276495db72) but that’s only because I didn’t understand git when I started this project). I have since become quite purist and do not wish to see any opinionated defaults added to normalize.css.*

I prefer the `overflow: auto` experience for pages as a default, but I also agree that it could be very application-specific. As this has been around for so long, I will defer to @mdo @fat @patrickhlauke and @battaglr — should this opinionated default be removed in v4, or should I just add to the adjoining comment that its an opinionated default and not a normalization? If there are no outstanding pros, I will just add to the adjoining comment.

**Comment by battaglr** [comment]
I think that —and this is an assumption— most websites/apps that use this library don’t need styles for `pre`, since it’s a tag/element that it's used just in a few circles, like in websites about code for example.

Considering —if we agree with my assumption— that most websites/apps don’t really need this, I would vote to remove it.

**Comment by jonathantneal** [comment]
Should we remove it, a PR has been made. I’ll wait for more feedback, and again, alternatively plan to mark it as an opinionated style.
