### ISSUE TITLE
Input Appearance 

### ISSUE THREAD

**Issue by emiluzelac** [necolas/normalize.css#344]
Howdy!

I am looking at this and trying to recreate what description is saying and can't replicate.

```
/**
 * Remove inner padding and search cancel button in Safari and Chrome on OS X.
 * Safari (but not Chrome) clips the cancel button when the search input has
 * padding (and `textfield` appearance).
 */

input[type="search"]::-webkit-search-cancel-button,
input[type="search"]::-webkit-search-decoration {
  -webkit-appearance: none;
}
```

Cancel icon works fine with padding present in both in Chrome and Safari on OS X. 

Thanks,
Emil

**Comment by jonathantneal** [comment]
Carried over from #499 ([test page](http://s.codepen.io/jonneal/debug/d89ae9ef94c37a395f2df3ecd292f88e)).

Chrome and Safari style `input[type="search"]` as `-webkit-appearance: searchfield; box-sizing: border-box;` which activates different default styles like the rounded borders. `::-webkit-search-cancel-button` stretches the layout in **Safari ≤ 8** as it adds the cancel button, and `::-webkit-search-decoration` adds additional padding around the text. Since support currently includes **Safari 6+**, we would need to keep these rules around.

Since I brought up `box-sizing: border-box`, I’m noting that normalize.css could normalize the `box-sizing` of search inputs to `content-box` to be more like other text inputs, but that would go against the grain of modern css preferences. Therefore, it’s almost an opinionated default to ignore this ua style. Not sure if you have any thoughts about this?

**Comment by battaglr** [comment]
@jonathantneal, awesome! Are we going to add the browser verions on the comments?

**Comment by bounasserabdelouahab** [comment]
He is a demonstration of what I wanted to say in the original post.
![search-padding-issue](https://cloud.githubusercontent.com/assets/1855505/13846161/0bc2f044-ec3d-11e5-856c-d92b390f5a31.gif)

As you can see in the animated GIF, the `-webki-appearnance: none;'` does get rid of the *×* button but not the padding, in other hand if we replace it with `display: none;` it perfectly solves the issue, at least in chrome, hope it helped!
