### ISSUE TITLE
Keep outline on links hovered or focused

### ISSUE THREAD

**Issue by lespacedunmatin** [necolas/normalize.css#357]
Hello !

On links hovered ou focused, you remove the outline (line 97). This harms the accessibility of the website : http://www.outlinenone.com/.

Could you please remove this rule ?

Thanks

**Comment by nickautomatic** [comment]
As far as I can see, this is definitely an accessibility issue. Removing focus styles by default means that unless people know to replace them, any site built on normalize.css as it currently stands will be difficult to navigate with a keyboard.

Your stated aim is to preserve useful browser defaults, and having a visual indication that an element is focused is definitely a useful browser default, because it makes the page keyboard navigable. That's an important accessibility consideration.

For more on the accessibility implications of removing focus styles, see eg. http://webaim.org/blog/plague-of-outline-0/
http://www.456bereastreet.com/archive/200905/do_not_remove_the_outline_from_links_and_form_controls/

**Comment by FagnerMartinsBrack** [comment]
Nobody is removing focus styles man, read the issue.

**Comment by nickautomatic** [comment]
Ah, sorry about that. You're totally right. I came here because I was working on making a project based on normalize keyboard-accessible, and found all focus styles missing, and - too hastily, I guess - jumped to the conclusion that normalize was to blame.

For what it's worth, my confusion was due to the comment in normalize ("Improve readability when focused and also mouse hovered in all browsers."), which set my expectation that I was looking at focus styles (I guess often you see what you're expecting to see...) Changing it to something like "when active and hovered" would avoid any (excuse for) confusion... :)
