### ISSUE TITLE
CSS file to be under copyright or license should have copyright notice

### ISSUE THREAD

**Issue by Nick-Levinson** [necolas/normalize.css#405]
When a *.css file is installed on a website, it is usually separate from any non-CSS files it came with in a Zip archive. So, a person reading the CSS file and wishing to copy it needs to know not only that there's a license but that it's under copyright so that a license is required. If you want to have the MIT license or any copyright license govern normalize.css, you should put a copyright notice in the CSS file itself and then you need to point to the license, either by providing the text of it in each file or by giving a URL for it. Simply writing "MIT License" is legally not notice enough of a copyright claim, under U.S. Federal law. I'm not a lawyer, so feel free to ask one, but right now an infringer would have the defense of innocent infringement, still illegal but with less of a cost to the infringer. Since you have reserved an obligation in the license, you evidently don't want your work released into the public domain.

The place to put the copyright notice is at the top or very near the top, before a mention of the license. Mention of the license should include a URL where it may be read in full text.

A similar issue for h5bp is already at the topic "need copyright notices and clearer license info inside CSS files #1655" (https://github.com/h5bp/html5-boilerplate/issues/1655), where it was suggested, I think, that I post separately here.

I'll be happy to add a copyright notice referring to whomever has the copyright to the copies of the CSS files I might install soon, if someone will post what that notice should say (normally it would be in the form of "Copyright [year/s] [creator/s]").

**Comment by superlukas** [comment]
I'd rather see *special* comments go away. Most people don't include CSS source code in production sites, and once they start compiling (i.e., merging, inlining) the code, the places those copyright notices appear are wrong anyway.

Depending on who you ask, the MIT license (and ISC, etc.) requires you to add the *entire* license to all copies (read: your website) — meaning you need a credits page. A lot of people argue "all copies" in this context means source code rather than binary (other licenses say "binary"). All I know is that compiled/transpiled/minified CSS and JS is not source code.

So, you really only have two choices: A custom (maybe generated) credits page per site, or no mentions at all. All creative interpretations in the middle are to vague for me. If you want to be safe, pick the first one. Giving credit is what all the cool kids are doing anyway.

Once you've done that, you can also safely strip all comments from the source code during compilation. I'm sure most judges would agree that including one copy of the license is enough.

I'm not a lawyer. (I'm Batman.)

**Comment by Nick-Levinson** [comment]
Copyright notice, to have the desired legal effect, has to be placed according to legal requirements, and that generally means where it is calculated to be seen by someone who otherwise would infringe in order to preclude innocense as a defense, that usually being at the beginning of the relevant publication (or unpublished item). I'm dubious that writing it on the home page so that it is visible to website visitors is sufficient for people who arrive at a *.css file without seeing the home page, especially when the *.css file is under a different copyright than is most of the site, although one could argue that someone could arrive at chapter 3 of a book without looking at the copyright page and is still bound by the book's notice, but then the copyright notice applicable to the *.css file would have to be written on the home page anyway. Claiming that copyright belongs to the website owner would be overclaiming, generally illegal unless there's at least a colorable claim to a basis for it, and writing a home page notice like "Portions copyright [year] [owner]" would avoid overclaiming but would fail to provide the notice needed for the *.css files in question.

If compilation strips all comments, that's a problem that needs a solution, probably by rewriting some comments back in or by redesigning the compilation tool so that some comments are preserved. Comments serve several purposes anyway, so a selective preservation feature would be a good idea anyway.

Credits are another matter and so is reprinting entire licenses. Those matters generally do not affect how copyright notice is to be provided. Providing a credits page probably does not solve the copyright notice problem, because it would be a separate page. One could add a comment to all pages in the source code to examine the credits page for all copyright notices, but that means preserving some comments in object code anyway.

It looks like HTML5 Boilerplate has a new version (5.0.0) and I haven't looked at that yet.

**Comment by superlukas** [comment]
Let me just quickly sum up all the things I've said in my last comment.

*When I say "the entire license," I'm actually saying "everything but the disclaimer."*

1. Copyright notices have no legal effect whatsoever.
2. You're required to add the entire license to the copy you distribute.
3. Nobody cares what file the license is in.
4. Stripping all comments is a problem if and only if the comment contained the entire license *and* you haven't added it somewhere else.

Alright, with that out of the way let me respond to some of your comment. You've mentioned this strange "innocence defense" that people can make (I assume it only works in the US). I'm pretty sure this scenario doesn't apply to software that has a file named "LICENSE" at the top of the directory.

I've already responded to your book analogy (3), but I want to give you an example. If you distribute a native app there's no sane way for you to add all licenses to the binary. That's it, really. Nobody cares what file the license is in.

> Credits are another matter and so is reprinting entire licenses. Those matters generally do not affect how copyright notice is to be provided.

You have to add the licenses anyway and the copyright notice is part of the license. And no, you don't have to add a comment to every file. I'm not sure what I have to tell you in order to convince you, but I strongly encourage you to have a look at Google Chrome's credits page and the PS4's credits page (or any random iOS app). Software has been shipped this way for a long time and while the web is a little different, neither the licenses nor the laws have changed.

You've also mentioned claiming rights that you don't actually have. Don't do that.

Still not a lawyer.

**Comment by Nick-Levinson** [comment]
Either you misunderstood what I wrote or someone else is going to have to sort this out to decide what H5BP's position should be. I'm happy to assume good faith on your part and I understood what you wrote the first time. I have some familiarity with U.S. law and that is the nation I'm writing about.

You wrote, "[c]opyright notices have no legal effect whatsoever." Yes, they do, of course. Maybe you didn't mean that literally. Innocent infringement is infringement that occurs when notice was not provided and, if a lawsuit for infringement follows, the defense affects the outcome so that it costs the infringer less, although infringement would still have occurred and there is still some cost to the infringer. In the U.S., as a result of the nation agreeing to a treaty, copyright notice is no longer required as an absolute requirement, but it is required in order to secure a certain benefit, that of precluding innocent infringement as a defense. I don't know what the law is on that point in any other nation, but it is part of U.S. Federal copyright law, and virtually every major publisher in the large U.S. market takes advantage of it by providing that notice, and that includes many software publishers.

About your comments #2 and #3 in your last post, the license is a separate matter beyond this topic's scope. I'm discussing the copyright notice. If publishing the license provides the copyright notice, that would be fine, but that wasn't the case the last time I looked in a *.css file from H5BP.

About your comment #4 in your last post, we disagree, and we disagree because you essentially argue that copyright notice need not be provided (also because you apparently believe that preserving any other comment (other than perhaps the full text of a license) in object code would never be useful but this topic is about copyright notice).

My book example was an argument in favor of your position, not against it, although I don't think it is enough of an argument to eliminate the need for notice in the *.css files.

The copyright notice was not in the *.css file I saw that mentioned the MIT license. Just mentioning the license is not a copyright notice. The copyright notice has to be explicit.

I was not recommending adding a comment to every file (although I do add comments myself); I pointed out that doing so would have the undesired effect you mentioned.

You wrote, "[y]ou've also mentioned claiming rights that you don't actually have. Don't do that." This suggests that you didn't read carefully. I wrote that doing so is "generally illegal". I don't think you need to advise me not to do it. I raised that particular point in case someone would argue that a simple copyright notice listing just the website owner as the copyright owner would suffice, that being a common practice. Your disagreement is on other points, not on that, so we agree that we shouldn't create illegal copyright notices.

I appreciate your advice that I "have a look at Google Chrome's credits page and the PS4's credits page (or any random iOS app)" but I don't have those things handy. But, again, I wrote and you quoted me as having written that "[c]redits are another matter". I'm discussing copyright notice. It has to be placed where it will have the desired effect. For example, in my experience, you cannot install Windows without, early in the process, agreeing to terms that explicitly state Microsoft's assertion of copyright. The notice is not merely somewhere else; it likely is also somewhere else, but it's explicitly in the terms to which you generally must agree in order to install Win.

One line in one comment at or near the top of each *.css file will suffice to state the copyright notice. I hope that's not too burdensome as a step for protecting the authors' rights. I've offered to add it to my copies of the HTML5 Boilerplate *.css files because it has an advantage for their authors and it's not too burdensome for me to do so. I just need to know what it should say. And I still recommend that it be added to downloadable *.css files from H5BP. That shouldn't be too hard or take too many bytes to affect website visitors' downloading speeds even through the slowest connections.

I generally log in to sites like these about once a week, so, if my present session ends too soon, I may not reply till next time. Thanks.

**Comment by superlukas** [comment]
Looks like I *completely* misunderstood you. My bad.

I'm going to cut this one short: What you're saying is that every CSS file (or any other file?) should contain a copyright notice at the top (in order to protect yourself) even if the license file already contains the copyright notice? (Under US law, that is) Did I get that right?

**Comment by Nick-Levinson** [comment]
Basically, yes, since I tend to be cautious about law.

CSS files are more likely than some others to be viewed as source code and therefore there needs to be English-language notice (not just machine-readable notice) in the file. My practice is to provide both English-language and machine-readable notice in every page's source code (I've generally written HTML or XHTML plus CSS) as well as notice that when interpreted by a browser will display notice where it can be seen by a non-techie visitor to the website (that last notice is usually at the bottom of a page but the source code has the other two notices in the head element or near the top in a comment). If the license itself contains the notice and it is reprinted in the file near the top and the notice is near the top of the license text, that will likely suffice, depending on layout etc. I'm not sure that the MIT license requires printing its full text in every file, as that could depend on whether "substantial portions of the Software" means every file (and if a file is an image or audio file that could be technically difficult, cumbersome, or impossible but "page" might be a possibility although I'm not sure the drafters of the MIT license meant page either), but if it is decided to publish it in full text near the top of the CSS file then that could be the basis for a solution.

**Comment by necolas** [comment]
Having read through the H5BP thread, I'm going to close/wontfix for the same reasons they did. Thanks for the input.
