### ISSUE TITLE
Mac Safari behave differently when body overflow-x hidden

### ISSUE THREAD

**Issue by BYODKM** [necolas/normalize.css#431]
`body { overflow-x: hidden; }` doen't work on Mac Safari (8.0.4) unless `html` has `overflow-x: hidden;`

[Live example 1](http://byodkm.github.io/overflow-x-test/index.html)
[Live example 2](http://byodkm.github.io/overflow-x-test/index2.html)

Proposal:

```
html { overflow-x: hidden; }
body { overflow-x: visible; }
```

**Comment by designbystephen** [comment]
This would not be an issue with or for normalize though. If you want that
behavior on your site, because it isn't a default, adjust your own styles
accordingly.  Good catch as far as style considerations go, save it to your
project if that's what you need.



Stephen Roth
designbystephen@gmail.com
(217) 201-5566

**Comment by BYODKM** [comment]
I understand what you meant.
That's why I wrote 

```
body { overflow-x: visible; }
```

which is default state, though.

**Comment by BYODKM** [comment]
I found `body { overflow-x: hidden; }` cause of vertical smooth scrolling issue on Safari. So it wasn't good idea anyway.
