### ISSUE TITLE
font-family

### ISSUE THREAD

**Issue by marekkobida** [necolas/normalize.css#480]
Why is there a monospace twice?

`font-family: monospace, monospace;`

**Comment by FagnerMartinsBrack** [comment]
https://github.com/necolas/normalize.css/commit/28f8e9b4d315691cba752ce77e1c329a2a5161a3#diff-bb3dde41d97f19be8ab7b4780a915d5eR166

**Comment by nicolasmccurdy** [comment]
I believe it's a bug fix for IE.

**Comment by briankoser** [comment]
[Reason](https://github.com/necolas/normalize.css/blob/2bdda84272650aedfb45d8abe11a6d177933a803/README.md#extended-details)

This has been asked in the past: #196, #293, #295, #326, #328, #335, #346, #347, #374, #415, #476

**Comment by kentfredric** [comment]
I should point out that I personally experience an additional bug that occurs as a result of this syntax.

For some reason there's some combination of Linux + Firefox + FontConfig that means that instead of `monospace, monospace` delivering a monospaced font, it returns a *serif* font. ( I dug into this a while ago because I stumbled into it on some other site, but I can't find it now :( )

Which for me, means `monospace, monospace` renders as Times New Roman. 

Bootstrap however doesn't exhibit this problem for some reason, which I suspect is due to them setting the font twice: https://github.com/preaction/Statocles/issues/420#issuecomment-168286500

**Comment by kentfredric** [comment]
This is how https://en.wikipedia.org/wiki/User:Davidgothberg/Test59 looks for me.

http://imgur.com/a/3tUJv 

But strangely, it looks different in the print preview.

http://imgur.com/a/hyMmS

**Comment by kentfredric** [comment]
Hah. After reading related firefox bugs:
- https://bugzilla.mozilla.org/show_bug.cgi?id=589779
- https://bugzilla.mozilla.org/show_bug.cgi?id=546315

It appears anyone who is experiencing this problem can make it go away simply by setting a monospace font explicitly in Firefox's advanced font preferences.

My understanding is that somehow that changes how the generics mechanisms work and "Fixes" the problem.

**Comment by kentfredric** [comment]
Ew :/. This problem is also dependent somehow on font-config settings. And ... I really can't be bothered with messing with those. I basically nuked the entirety of `/etc/fonts/conf.d` except for the `infinality` rules and that also seems to be sufficient to fix the "monospace,monospace dun goofed" issue.

**Comment by necolas** [comment]
Interesting quirks @kentfredric!
