### ISSUE TITLE
Ending oldIE support?

### ISSUE THREAD

**Issue by AllThingsSmitty** [necolas/normalize.css#482]
Support is currently provided for IE8+. Microsoft support for IE < v.11 [ends on January 12, 2016](https://technet.microsoft.com/en-us/ie/mt163707). Should we be now talking about eliminating some much older versions of IE from support, e.g., IE8-9 or more? Perhaps Normalize v.4?

**Comment by nvartolomei** [comment]
There are so few specific things for IE8-9, does it really matter saving 20 bytes?

**Comment by AllThingsSmitty** [comment]
All the more reason to just drop oldIE support.

**Comment by thierryk** [comment]
> Microsoft support for IE < v.11 ends on January 12, 2016

In my opinion, what's *relevant* is how many people are still using versions older than v.11&mdash;and I think that number is significant.

**Comment by fleeting** [comment]
Just for reference, the [lifecycle support chart](https://support.microsoft.com/en-us/lifecycle#gp/Microsoft-Internet-Explorer) shows they will be supporting IE9 and IE11 on desktop Windows. Not sure if the original statement is accurate of only supporting IE11.

**Comment by tunelinks** [comment]
If you read the chart it only mentions 'Windows Vista SP2' and 'Windows Server 2008' which I imagine is a small number of consumer users on IE9.  And that support is geared more towards business and enterprise anyway.

**Comment by ansballard** [comment]
According to CanIUse, IE9 still has 1.1%, which isn't insignificant.

**Comment by Yeswanth-JG** [comment]
If you consider countries like India, Still people are into IE8 & IE11... but very less in count when we consider IE9 & IE10 users in India. But outside India, most industrialised countries are updated their systems. So, more chances are users regularly upgrading to IE11. Always, everywhere, it will be very less people who are using IE9 & IE10.
---
The main problem is with IE8. We can create a major upgrade to Normalize under v4, which will get rid of <IE11 support.

**Comment by ppKrauss** [comment]
This difficulty to ending oldIE convinced me to "fork" a sibling project... It make sense here?  It is easy to maintain.

[**This adaptation of  Normalize.css**](https://github.com/ppKrauss/normalize-noIE.css) (cutting away ~1/3 of code by removing IE support) can be used with [web applications](https://en.wikipedia.org/wiki/Web_application) optimized for non-MS browsers, or in production environments where the user has no option to use IE.

**Comment by nvartolomei** [comment]
You just saved 139 gzipped bytes :)

**Comment by ppKrauss** [comment]
Yes, 139 is better tham 20 bytes ;-)
It is smaller, faster, and can be used in environments where the IE compatibility  would cause problems of its own.

*Another option is to maintain [`normalize-noIE.css`](https://github.com/ppKrauss/normalize-noIE.css) here*, to bring together onother audience, expanding community and collaboration.

PS: people have [practical](http://blog.jquery.com/2013/04/18/jquery-2-0-released/), [historical and ideological](https://en.wikipedia.org/wiki/Microsoft_litigation) motivations to cut IE.

**Comment by AllThingsSmitty** [comment]
I assume Edge and IE11 support is included with this sibling project? The intention isn't to remove IE support altogether, just oldIE.

**Comment by ppKrauss** [comment]
@AllThingsSmitty,  this is why it is a "sibling project", and a different name for CSS file (*normalize&#8209;noIE*). It is only for a specialized use. The proposal is not to change *normalize.css*.

I am commenting here because it is, perhaps, an option to better negotiation here: 

* users (ex. [India commented here](#issuecomment-147600626)) that need oldIE, negociate here more time.

* users that "need no IE" (ex. [community that I commented here](#issuecomment-152823864)), does not interfere in this negotiation, they can use   *normalize&#8209;noIE*.

**Comment by AllThingsSmitty** [comment]
I thought the intent here was to submit a proposal or PR for moving Normalize to v.4 which wouldn't have [<IE11 support](http://www.sitepoint.com/browser-trends-october-2015-sustained-safari-slips/), whereas v.3 would still have it?

**Comment by ppKrauss** [comment]
@AllThingsSmitty , Yes, I think it is. V3 is the current version, v4 is the future. Your "Ending oldIE support" proposal is to v4: the people here (in this discussion) are negociating the future.

Hum... in that context I said something like  "the *normalize‑noIE* proposal is not to change *normalize*"... Well, to avoid context confusions, [I posted the *normalize‑noIE* proposal here](https://github.com/necolas/normalize.css/issues/485).

**Comment by jonathantneal** [comment]
I’m open to deprecating IE8 in v4 or v5, providing a clear warning, and then outright removing support in v5 or v6. However, I’m not interested in ending support in v4.

As a fan of moving the web forward, that probably deserves an explanation. So, I’m thankful for all the folks who have already shared, because I share their concern, which is — whenever we’re talking about impact, I want to avoid thinking with percentages.

I had a great conversation with a developer at Wikipedia one time. I was being really cavalier about “0.1% of page views” which I thought were just, like, totally insignificant. Well, it turned out that 0.1% of page views represented something like 109 million people, and mostly people in areas where access to the internet was limited. This developer wasn’t trying to boast when they explained this to me, and I hope it doesn’t come across that way here either. It hit me like a ton of bricks.

So, if Normalize.css powers [tens of millions of sites](https://github.com/necolas/normalize.css/issues/500#issue-128029978), and if each site gets just 1 visitor, then 1.1% of our audience already represents roughly 110,000 people (or, for anybody on the US West Coast, the entire population of Berkeley, California).

Are a few bytes worth the effort on a project the scale of Normalize? My answer is hell yes. It **doesn’t** mean everything has to look the same, and it **does** mean it’ll take extra work and testing, but people come first.

Apologies for the long answer, but I think the question of dropping support is really valid and deserves a legit reply.
