### ISSUE TITLE
Extra 3px padding-right in seach input fields.

### ISSUE THREAD

**Issue by bounasserabdelouahab** [necolas/normalize.css#499]
I had an issue that almost drove me crazy when I was styling input fields, for some weird reason, my search inputs seemed to have extra padding to the right (`3px` or so) which caused some styling issues where search input icons didn't align perfectly with other input icons, this issue was existent only in webkit browsers, I had no idea what was going on.

long story short, after 2 hours of headache I found that the problem is caused by the use of `-webkit-appearance: none;` at [line 368](https://github.com/necolas/normalize.css/blob/master/normalize.css#L368) which is used to remove search cancel button in webkit browsers, but it didn't remove the button completely, this is obviously a browser bug, I just wanted to say that by changing `-webkit-appearance: none;` to simply `display: none;` does fix the problem, thank you.

**Comment by jonathantneal** [comment]
I’m unable to recreate a fix using your technique ([citation](http://s.codepen.io/jonneal/debug/d89ae9ef94c37a395f2df3ecd292f88e)).

Chrome and Safari style `input[type="search"]` as `-webkit-appearance: searchfield; box-sizing: border-box;` which activates different default styles like the rounded borders. `::-webkit-search-cancel-button` stretches the layout in Safari ≤ 8 as it adds the cancel button, and `::-webkit-search-decoration` adds additional padding around the text.

Since I brought up `box-sizing: border-box`, I’m noting that normalize.css could normalize the `box-sizing` of search inputs to `content-box` to be more like other text inputs, but that would go against the grain of modern css preferences. Therefore, it’s almost an opinionated default to ignore this ua style.

**Comment by jonathantneal** [comment]
Continuing this issue in #344
