### ISSUE TITLE
Opinionated font family

### ISSUE THREAD

**Issue by jonathantneal** [necolas/normalize.css#517]
The [`font-family`](https://github.com/necolas/normalize.css/blob/master/normalize.css#L10) is defined on `<html>` as `sans-serif`. I’d like to look into whether this is normalizing a style, adding a missing feature, correcting a bug, or applying an opinionated default.

**Comment by battaglr** [comment]
If this is not taken, I would like to take a look at this.

**Comment by jonathantneal** [comment]
@battaglr, certainly, and please do.

**Comment by battaglr** [comment]
Here are [the results](https://gist.github.com/battaglr/b76e419badd4a1d0b24e) of the [test case](https://jsfiddle.net/battaglr/jxaoh6u8/) on different browsers and platforms.

As shown by the results this is indeed a normalization, since most browsers use some variation of a `serif` typography and all —tested— browsers on Android use `sans-serif`.

That being said, in all my years doing web stuff I haven't been involved in a project in which the `font-family` wasn't explicitly declared, so I think this could be removed without a mayor impact.

If you consider that we should remove the `font-family`, I'll be glad to do a PR.
