### ISSUE TITLE
Value of `margin` for `body` seems opinionated

### ISSUE THREAD

**Issue by battaglr** [necolas/normalize.css#518]
We are currently defining a [`margin` of `0` for the `body` element](https://github.com/necolas/normalize.css/blob/3.0.3/normalize.css#L15-L21). As stated in the test file, apparently [this is an opinionated value](https://github.com/necolas/normalize.css/blob/3.0.3/test.html#L94-L98).

Is this something we want to keep anyway or is it OK if I do some research about this particular property?

**Comment by jonathantneal** [comment]
Yes, we really should take a look.

I’ll want to coordinate any changes we make to this with the bootstrap team, since they are not overwriting normalize.css here.

@patrickhlauke, many people have been contributing tests and screenshots to narrow down exactly which versions of browsers are affected by normalize.css. In that process, we’ve found that some rules are not normalizations. Those rules, when used vanilla, sometimes hinder the display of things, and `body { margin: 0 }` may fall under this category.

Would you be comfortable adding this to your reboot? The goal is for normalize.css to fix missing/broken/inconsistent/non-spec styles and generally make things *just work*™, but not introduce opinionated defaults.

**Comment by battaglr** [comment]
@jonathantneal, great! During the week I'll prepare some test cases to see if any normalization is really needed, so we can do an informad decision about this alongside with de Bootstrap team.

**Comment by patrickhlauke** [comment]
bootstrap does indeed rely on having the `{ margin: 0 }` (for full-bleed elements), so quite happy to add it to your reboot in coordination with its removal from normalize /cc @mdo

**Comment by necolas** [comment]
I think removing the default margin from `body` is pretty much essential. Despite the name of the project, it has intentionally never been about pure normalization. And bootstrap isn't the only consumer of the project.

**Comment by battaglr** [comment]
I'll not argue that a `margin` of `0` in the `body` element is not a good default; and a change on this property will certainly have a huge impact on most projects/websites that rely on that.

Lately "pure normalization" was the direction taken; but we can —and guessing by your comment, should— try to identify in which cases is okay to be "opinionated" in favor of a widely used default and in which not.

I don't have a strong opinion on this matter, but I do think that if the "pure normalization" path were taken, usually we would need —unless using BEM or some other methodology— an extra set of rules to act as baseline —here I'm talking about Bootstrap's Reboot, Sanitize.css, etc.

**Comment by mdo** [comment]
> I think removing the default margin from `body` is pretty much essential.

I'm inclined to agree.

**Comment by battaglr** [comment]
Closed by #529.

**Comment by jitendravyas** [comment]
Was it decided to remove the margin? I don't see an agreement here though.

**Comment by jq-87** [comment]
yeah please add it back.

**Comment by jonathantneal** [comment]
@jq-87, @adamgruber may be creating a soft reset we will link to in the project README.md.

I would be very open to creating a list of soft resets that leverage normalize.css with short descriptions of how they work. I was hesitant to create such a list if only sanitize.css was going to be on it (it seemed too self-referential). I know people have similarly asked for / pleaded for / demanded a similar soft reset for forms.
