### ISSUE TITLE
Why is -webkit-appearance: button  used?

### ISSUE THREAD

**Issue by SteveALee** [necolas/normalize.css#566]
I searched the issues but could not find the justification for this. 

I thought the idea for normalize is to give a common starting point for css but this does exactly the opposite by giving weird style on iOS.

Took a while to find this one ;)

thanks

**Comment by battaglr** [comment]
@SteveALee, hi! [As stated in the comment](https://github.com/necolas/normalize.css/blob/master/normalize.css#L296), this allows us to style *buttons* on iOS —styles that otherwise will be ignored.

In the screenshot below, the second button —an `<input type="button" />`— doesn't have the `-webkit-appearance: button;` property.

> ![ios_iphone-4s_5 1_portrait](https://cloud.githubusercontent.com/assets/1921409/14302542/7a6ca978-fb78-11e5-8ab2-2c888e2a2cff.jpg)

Does it make more sense now?

**Comment by SteveALee** [comment]
Are you saying that without that style no other styles can be applied?

Strange as I'm sure I removed it and could still set my styles. But maybe was as I removed after your CSS rule. Or perhaps I was mistaken as styling is very light. I can't check right now.

**Comment by SteveALee** [comment]
If it is required how do we remove those rounded ends and other iOS native style things?

**Comment by oreqizer** [comment]
imo it would make more sense to use it when it's needed, not in a normalizer

f.e. it breaks Material UI's MenuItem

**Comment by battaglr** [comment]
@oreqizer, why would you say that? And FWIW, that's a *bug* on Metarial UI, please, see: #554 and https://github.com/callemall/material-ui/issues/4008.

**Comment by oreqizer** [comment]
i really have no arguments for my statement, it's just it felt at that time, because it was making me really confused trying to figure out what was going on

i understand it's use now, however. i'll go ahead and check out the material-ui issue

**Comment by SystemDisc** [comment]
I'm using normalize.css and Bootstrap 3.3.X. If I create a label with `class="btn btn-default btn-block"`, I expect it to look like this:
<img src="http://i.imgur.com/FjWIzQ2.png">

Instead, because of `-webkit-appearance: button`, which I agree should not be part of normalize.css, it looks like this:
<img src="http://i.imgur.com/ry0f2dp.png">

This is in Chrome 56.0.2924.87 (64-bit) on macOS Sierra.

**Comment by realty-video** [comment]
just fixed this wrong behaviour in my project, "bootstrap": "4.5.2":

[type=button], [type=reset], [type=submit], button {
  -webkit-appearance: none;
}

**Comment by mikkorantalainen** [comment]
As far as I know, `-webkit-appearance: button` asks for *custom* rendering to match system native button rendering. If you want all CSS properties to have their normal effect, you should use `-webkit-appearance: none` instead.
