### ISSUE TITLE
Correct the inability to style select fields on Mac

### ISSUE THREAD

**Issue by Yapaslfeu** [necolas/normalize.css#572]
I know I'm insisting (cf. #151) but, if you don't turn off the Aqua effect on Mac, you'll never be able to stylize the select fields!!

Simply try the above, and you'll see that no styling is applied to the field on Mac:
`<select style="height: 200px; font-size: 40px;"></select>`

Except if we turn off the Aqua effect, doing at least 1 of the 3:
- set the -webkit-appearance to menulist-button
- modify the border (color, width, radius, image or whatever)
- modify the background (color or image)

**Comment by jonathantneal** [comment]
This will be considered for a few reasons, but I’m not yet sure whether it belongs in Normalize.css 4 or 5.

The reason I’d consider it is because `menulist-button` really does resolve the issue while retaining OS styles. Also, it makes `<select>` behave consistently between MacOS Safari and iOS Safari.

At worst, we can leave a note in the README.md describing the situation and a solution like:

```css
select:not([multiple]):not([size]) {
  -webkit-appearance: menulist-button;
}
```

@battaglr, would you give this a second look? See: http://s.codepen.io/jonneal/debug/bae45a37545f26c12c29eeb5f7e90638

**Comment by Yapaslfeu** [comment]
Thank you for your answer!
In fact, the fix should apply on Mac only, but i don't know how to target this.

On Windows, we have the following:
- Edge supports the border and background fixes, but not the -webkit-appearance one, which change completely the field design
- IE and Firefox only accept the -webkit-appearance fix, the other fixes changing completely the field design
- Chrome accepts all the 3 above fixes

**Comment by jonathantneal** [comment]
In this case, I would say this is not something we can safely normalize.

**Comment by Yapaslfeu** [comment]
It must be, or you can't apply any style to select fields on Mac and iPhones!!!
This is a low level problem and is exactly the same than the one you're fixing in line 294 "2. Correct the inability to style clickable types in iOS."

Why not using this:
select {
    -webkit-appearance: menulist-button;    /* Mac Aqua off */
}
@supports (-ms-accelerator:true) {
    select {
        -webkit-appearance: menulist;    /* Revert Aqua for Edge */
    }
}
