### ISSUE TITLE
Resetting h1 encourages non-semantic html or bloated stylesheet

### ISSUE THREAD

**Issue by mizurnix** [necolas/normalize.css#609]
In html5 era h1 has wider semantic usage and it's encouraged both for SEO and for accessibility to use it as the first heading of parent section. Some may argue and continue using only one h1 per page, but those of us who happen to use the approach I described together with normalize.css have to either go non-semantic or bloat there stylesheet with extra styles.

The problem is caused by the fact that normalize.css resets h1 and sets it to equal size throughout the page. But not all h1-s are created equal. View my examples below to see what I mean:

[Example 1](https://jsfiddle.net/mizurnix/5r9daeux/)
[Example 2 (same html, added normalize.css)](https://jsfiddle.net/mizurnix/adscyqv6/)

I understand that normalize.css is not some sort of a typography framework to handle all those cases with headings, but in that case, maybe it's better to un-normalize h1 as well. That way, people will not be tempted to use h4 as a heading for their article block.

**Comment by thierryk** [comment]
@mizurnix you say:

> In html5 era h1 has wider semantic usage and it's encouraged both for SEO and for accessibility to use it as the first heading of parent section.

but this is not true because there are currently no known implementations of the outline algorithm in graphical browsers or assistive technology user agents [1]. To the contrary, it is recommended to use `h1-h6` to convey structure [2]. This has also been discussed in various articles [3][4].

[1] https://www.w3.org/TR/html5/sections.html#outlines
[2] http://w3c.github.io/html/sections.html#the-h1-h2-h3-h4-h5-and-h6-elements
[3] https://www.paciellogroup.com/blog/2013/10/html5-document-outline/
[4] http://adrianroselli.com/2013/12/the-truth-about-truth-about-multiple-h1.html

**Comment by mizurnix** [comment]
@thierryk thanks for clarification. I guess I was kind of outdated on this and relied too much on visual behaviour of Chrome/Firefox with h1-s inside section/article elements

**Comment by thierryk** [comment]
@mizurnix no worries. Many people still think it is best practice to use multiple `h1` since that was the original idea...

**Comment by dustinboston** [comment]
@thierryk I get that the outline algorithm may not bt implemented, but the CSS to support H1s definitely is in Firefox and Chrome. It is possible that the w3c isn't aware of this yet, and should update their warning. Whether it is valid syntax is not the point of normalize. Browsers *are* using it, so it should be normalized.

In this case, it seems like it would be better to copy the rule from either Firefox or Chrome to support Edge/IE rather than killing a potentially useful feature. Check out the "Go vegan..." headline, and HTML in the screenshots below.

Firefox:

![image](https://user-images.githubusercontent.com/647464/40892282-cf2495e0-6749-11e8-9904-1fdd31c88c6b.png)

Chrome:

![image](https://user-images.githubusercontent.com/647464/40892340-a37c459a-674a-11e8-8cbc-6c2f1fe27a32.png)
