### ISSUE TITLE
img[usemap] is color:#00f in Firefox's default stylesheets

### ISSUE THREAD

**Issue by jsit** [necolas/normalize.css#617]
Would like to see something like `img[usemap]{color:inherit;}` in normalize.

**Comment by thierryk** [comment]
My suggestions:

   * FF applies the same styling to `object[usemap]` so if this is also unique to FF it may make sense to style that as well. Unless we consider there is no real need to do that since this is now *obsolete* ([object element usemap should be deprecated](https://github.com/w3c/html/issues/285)).
   * I would not qualify the selector&mdash;drop `img` to lower the specificity (go with `[usemap]` instead of `img[usemap]`)
   * What about using the `currentColor` keyword instead of `inherit`?

**Comment by jsit** [comment]
Thanks @thierryk, I've updated my PR to include your suggestions.

**Comment by jonathantneal** [comment]
I would ask that you add a test, preferably to test.html but optionally in its own CodePen. Once I’ve validated it against all the browsers, I’ll be happy to merge. Thanks!

**Comment by jsit** [comment]
Actually, on second thought, since anything with `[usemap]` is technically a link -- isn't inheriting the browser's default text link color actually the correct behavior?

**Comment by jonathantneal** [comment]
If there’s a cross browser inconsistency, share a CodePen showing it off, and I’ll run the tests and verify if the suggested fix works.

**Comment by mattbrundage** [comment]
@jsit, you're right, it _is_ technically a link. And Firefox's default color for usemaps, `#00f`, is actually not far off from their default link color, `#00e`. But normalizing link colors is something that this project has intentionally avoided doing.

**Comment by jsit** [comment]
> normalizing link colors is something that this project has intentionally avoided doing.

@mattbrundage Sounds right to me. Closing.
