### ISSUE TITLE
Jekyll bug

### ISSUE THREAD

**Issue by zachdyer** [necolas/normalize.css#656]
When I loop over the pages on my jekyll site it picks up on one of your files that your created.

However I don't see that file in my directory.

`{% assign sorted_pages = site.pages | sort:"order" %}`

`sorted_pages.url` will output `/assets/css/style.css` in the loop. And at the top of the file has your name on it with your github url.

**Comment by necolas** [comment]
Sorry but there's nothing here that is going to be causing that issue

**Comment by Philzen** [comment]
The easy workaround for anybody experiencing this issue and coming to this page (as mentioned [over at jekyll #7478](https://github.com/jekyll/jekyll/issues/7478)):

```
theme: null
```

It seems to be caused by github-pages (which apparently includes your normalize.css) and it still persists in the current version (204).
