### ISSUE TITLE
How about a new version that drops ie9 support?

### ISSUE THREAD

**Issue by ShaggyDude** [necolas/normalize.css#666]
I would like a normalize edge version that is targeted at all (last two).

**Comment by bronzehedwick** [comment]
I would argue that if an edge version of normalize were created, to only target browsers that Microsoft itself supports, i.e. IE 11, and latest 2 versions of Edge.

**Comment by dagnelies** [comment]
I don't see the benefit of this. As it is, normalize is < 1 kb. Are you really wanting to drop support for IE9 just to spare a few bytes?! Silly idea IMHO.

**Comment by ShaggyDude** [comment]
I don't understand why for all other browsers 'last two' is generous but IE gets special treatment. Let's push the platform forward and give old browsers an upgrade message.

**Comment by ShaggyDude** [comment]
Let's also be clear. I am suggesting an edge version. One would be free to use the existing version if they work somewhere where they can't upgrade browsers easily (schools).

**Comment by jonathantneal** [comment]
Internet Explorer is a special use case because it is tied to Windows releases, which limit user upgrade paths.

If one wanted to automate removing those unnecessary bytes for themselves and the rest of the webdev community, they could take advantage of the fact that every part of normalize lists the browsers it targets, which means one could write a [PostCSS](https://github.com/postcss/postcss) plugin that omits the rules that do not match a [browserslist](https://github.com/ai/browserslist) config.

I’d definitely provide link to that project in our README.

**Comment by ShaggyDude** [comment]
NM guys. this is what I'm looking for. http://jgthms.com/minireset.css/

**Comment by jonathantneal** [comment]
@ShaggyDude, looks good.
