### ISSUE TITLE
Suggestion: set font width for nice 'rem' usage.

### ISSUE THREAD

**Issue by 8lall0** [necolas/normalize.css#711]
`font-size: 62.5%;`
so 1rem = 10px.

I think that it's so useful it "must" be put here.

**Comment by jacty** [comment]
You should put it in your own css files instead of normalize.css. Normalize.css is mainly for fixing browser inconsistencies.

**Comment by tomasz1986** [comment]
First of all,  `1rem` depends on the OS / browser DPI and zoom levels, and thus can be very different in each system configuration. There is no rule that `1rem` = `16px`, especially today with all the different displays, including the HiDPI ones.

**Comment by jonathantneal** [comment]
Hi @8lall0, thanks for checking out the repository. I do think you’re issue has been addressed:

1. This is a duplicate of #416.
2. This neither preserves a default, corrects a browser bug, or resolves browser inconsistencies.
3. A major feature of `rem` is that it gives some control of text readability over to the user. It is acknowledged that this power is largely lost to users because many developers force px font sizes upon sites, and because many site interfaces break when the font size is independently zoomed, and because browsers obscure text zooming controls. [Citation 1](https://practicaltypography.com/point-size.html), [Citation 2](https://nicolas-hoizey.com/2016/03/people-don-t-change-the-default-16px-font-size-in-their-browser.html).

I hope this helps. 😄

**Comment by 8lall0** [comment]
Thanks a lot guys :)
Closing.
