### ISSUE TITLE
Normalize font rendering on Safari

### ISSUE THREAD

**Issue by drify** [necolas/normalize.css#716]
For example, if you give one element `position: fixed` , Safari will promote it to a compositing layer, which changes font smoothing and makes the text thinner and blurred. This problem was not fixed until quite recently (High Sierra) [[1]](https://bugs.webkit.org/show_bug.cgi?id=23364#c65) . Chrome seems more clever when promoting elements and doesn't suffer from this bug. 

One "solution" is to force `-webkit-font-smoothing: antialiased` so that fonts are rendered consistently. Similar requests like [#683](https://github.com/necolas/normalize.css/issues/683) were not accepted, because that changes browser's default behaviour and actually degrades text in most cases. 

However, applying `-webkit-font-smoothing: subpixel-antialiased` **also** can fix this bug and **normalize** browser styles (as it's the default). I'm not sure if this code will break other things, please tell me if so. 

References: 
1. https://bugs.webkit.org/show_bug.cgi?id=23364 
2. https://stackoverflow.com/questions/22204752/mac-safari-font-rendering-changes-thinner-when-any-element-on-the-page-gets-posi 

A related fiddle: http://jsfiddle.net/t4e4x/ . Even the latest version of Safari has a similar problem in an iframe.

**Comment by gouch** [comment]
This fix seems a little unpredictable to me. I tried your demo by [adding](http://jsfiddle.net/t4e4x/2/) `-webkit-font-smoothing: subpixel-antialiased` to body:

It looks like `subpixel-antialiased` doesn't guarantee *subpixel* AA will be used. I see in Chrome and Safari that in conditions (animation/movement/position:fixed) that normally trigger the drop from subpixel to grayscale AA that instead of actually using subpixel AA (colored pixel blend) it uses a slightly heavier grayscale AA (it's thicker than `aliased`).

There's also the problem of testing this at JSFiddle at all, because that site sets font smoothing in its own CSS for the fiddle area, and I imagine the positioned iframes used for viewing the result factor in to the browser's algorithm on which font smoothing to use.

Personally, font smoothing seems a low level browser optimization (often changing) and I'd rather let the browser run its algorithm and decide which AA is best and I can fix it on a case-by-case basis when I definitely know it got it wrong (akin to `will-change`).

**Comment by necolas** [comment]
> I can fix it on a case-by-case basis 

I think this is the recommendation

**Comment by d7mtg** [comment]
I'm a bit late, but try `font-synthesis: none;`
