### ISSUE TITLE
should the paragraph <p> tag have 0 margin-top?

### ISSUE THREAD

**Issue by v4nnig** [necolas/normalize.css#765]
Hi there, 

Has i understand normalize.css make all the margins to 0, so in this case why still exist a margin top?

Seems the <p> it has the margin, but normalize.css says `body { margin: 0}` this should affect to the `<p>` tags too right???

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css">
    <title>Document</title>
</head>
<style>
    p {
        background-color:red;
        /* margin: 0; */
    }
</style>
<body>
    <p>This text should have 0 margin top?</p>
</body>
</html>
```

![image](https://user-images.githubusercontent.com/5842564/46067114-591a5600-c176-11e8-85a9-5f6fa0a0e878.png)

**Comment by Elstermann** [comment]
> Has i understand normalize.css make all the margins to 0, so in this case why still exist a margin top?

Thats not the case at all. Heres what normalize.css (according to https://github.com/necolas/normalize.css):

# What does it do?

- Preserves useful defaults, unlike many CSS resets.
- Normalizes styles for a wide range of elements.
- Corrects bugs and common browser inconsistencies.
- Improves usability with subtle modifications.
- Explains what code does using detailed comments.

## In other words

normalize.css normalizes default behaviors between browsers. The default behavior of `p`aragraphs is `margin-top: 1em`. So normalize.css doesn't **reset** this behavior as it is correct in general. And if [you have a look at the source code](https://raw.githubusercontent.com/necolas/normalize.css/master/normalize.css) you will see that it also doesn't **set** it to its default behavior (which again is `margin-top: 1em`) which means that there is no need to do so because "all" browsers have implemented the default behavior correctly.

-----------------------
_hope it helps_

**Comment by garrettw** [comment]
`body { margin: 0}` does not affect the `<p>` tags -- only `<body>`.

**Comment by v4nnig** [comment]
> > Has i understand normalize.css make all the margins to 0, so in this case why still exist a margin top?
> 
> Thats not the case at all. Heres what normalize.css (according to https://github.com/necolas/normalize.css):
> 
> # What does it do?
> * Preserves useful defaults, unlike many CSS resets.
> * Normalizes styles for a wide range of elements.
> * Corrects bugs and common browser inconsistencies.
> * Improves usability with subtle modifications.
> * Explains what code does using detailed comments.
> 
> ## In other words
> normalize.css normalizes default behaviors between browsers. The default behavior of `p`aragraphs is `margin-top: 1em`. So normalize.css doesn't **reset** this behavior as it is correct in general. And if [you have a look at the source code](https://raw.githubusercontent.com/necolas/normalize.css/master/normalize.css) you will see that it also doesn't **set** it to its default behavior (which again is `margin-top: 1em`) which means that there is no need to do so because "all" browsers have implemented the default behavior correctly.
> 
> _hope it helps_

Ok, i understand thanks
