### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by ZaDarkSide** [necolas/normalize.css#805]
Now it's 2020 lots of issues and pull requests remain unanswered.
Is this project dead? If yes either archive the project or set a new owner that can maintain it.

**Comment by thwaller** [comment]
I wondered the same when looking at this and other similar projects. Over a year of no updates while others are more current. I agree 100% with your proposal, archive it so users are informed that updates are not coming, or at least make it clear that if there are any updates, any sort of timeline is unknown.

**Comment by Toddses** [comment]
necolas rolls in periodically and manages some PRs and issues, but has not pushed a lot of releases recently. Realistically speaking, the project is pretty stable, which is why you don't see a lot of action. We still use normalize.css on every single project as I'm guessing many others do as well. I would not call it a "dead project" necessarily, it serves the same purpose it has always served - base styles so you get defaults that are normalized across all browsers.

**Comment by ZaDarkSide** [comment]
Well just reading the code and the issues, a default value of `line-height: 1.5` on the html was never addressed, most of the additions are ignored because they are considered resets and not normalization, basically having 7.8k forks of this project tells me that people want more changes merged into it or they will fork it and add them themselves. Believe it or not but people now consider using a library if it is popular, if it is updated regularly, if there is activity around it, even if the code is stable the 7.8k forks says that is stale and new developers that discover this library will be reluctant to use it because of this.

**Comment by Toddses** [comment]
This project has historically encouraged forks so people can add their own, opinionated normalizations and resets. Believe that's why you see a lot of forks. And many of those forks are ancient, meaning there's a non-trivial number of forks prior to the last year of "inactivity".

I'm not disagreeing with the sentiment in principle. I just think this is a scenario where a stable set of rules is desirable. This project has historically been strictly managed to carefully maintain this stability, the need to remain a normalization (not a reset), and the ability to fork and customize per project.

It's obviously a popular library (180k + dependents). Archiving sends the wrong message.

**Comment by thwaller** [comment]
A stable project is not always a good project. Normalization require testing and specifics change with time, developer styles and browser changes. Stable says it should give little to no errors, but does it really fill the need like others do? That is the point here. Not disagreeing with you, just making the other side of the case. I opted for a different base as it is updated and issues remain active.

**Comment by ZaDarkSide** [comment]
@thwaller Well can you point us for your alternative of choice?
I am looking also for an up to date css normalization and/or reset.

**Comment by thwaller** [comment]
I opted for this one. I cannot say how well it works as I just added it today, but I can say there are no issues or errors caused by it. All I can say for sure is that it is active and is included in cdnjs.

https://github.com/sindresorhus/modern-normalize

**Comment by mvasilkov** [comment]
@ZaDarkSide I've attempted to create one such library based on normalize, going for some of the "modern" CSS features like

* using system fonts by default
* using the best monospace fonts available for `pre` `code` and such (incl. SF Mono)
* optional SCSS for easier integration, and some customization via `!default` variables
* preserving more useful browser defaults

https://github.com/mvasilkov/systematize

It's not widely used at the moment, so it's possible to introduce changes without worrying too much. If you're interested in such a project, let's discuss!

**Comment by ZaDarkSide** [comment]
Thank you both for your answers, I will evaluate them and choose what is most suitable for my project.

**Comment by thwaller** [comment]
@mvasilkov - thanks for sharing. I will check it out as well.

**Comment by tabroughton** [comment]
I thought the same as @ZaDarkSide especially as Edge browser now using chromium etc.  It would be great to get @necolas opinion

**Comment by polarathene** [comment]
I see that @necolas closed the issue without comment. No PRs merged, last update was still back in 2018.

Wouldn't it be better to keep this issue open and pinned? Perhaps change the title to "Status of normalize.css" or something? Otherwise will likely get other issues like this one popping up again. The discussion here should be all that users need to see if they have this question?

**Comment by ghost** [comment]
Hey, There I used normalize.css and all of its children (normalize.css based css resets) to learn about css resets and how to make them better. I created a more powerful and better css normalize called reseter.css. Feel free to tell me about modifications than can make my reset better. Thanks :)

Repo: [krishdevdb/reseter.css](https://github.com/krishdevdb/reseter.css)

**Comment by nuxodin** [comment]
I created "norm.css" and "base.css" that I keep updated.

**norm.css:** just crossbrowser normalisation, no opinionated styles.
https://github.com/u1ui/norm.css

**base.css:** usefull defaults:
https://github.com/u1ui/base.css

I would appreciate a little more community.

Also listed under "resources", many different similar projects that I have found.
https://github.com/u1ui/norm.css#resources
