### ISSUE TITLE
Is this library still functional/relevant/maintained as of 2021?

### ISSUE THREAD

**Issue by ben-rochlin** [necolas/normalize.css#856]
As the title describes, my issue is in wondering if this library is still relevant/practical and functional as of 2021 or if there are any alternatives that would be more suited?

thanks.

**Comment by miquelfire** [comment]
I would say the lack of maintenance is the only issue with this project.

I'm fairly certain there's rules can be removed because it targets IE10 users, but is not needed for IE11 (Assuming IE support is important at all now a days for a library like this). At some classic Edge support should be given the same treatment as IE support. Windows versions with classic Edge are still being supported however, so it's not dead yet.

**Comment by maurer2** [comment]
There are a couple of alternatives that are actively maintained:

* Sanitize.css (https://github.com/csstools/sanitize.css) [Edit: Seems to be unmaintained as of 2022] [Edit: development has picked up again as of 2026]
* Modern-normalize (https://github.com/sindresorhus/modern-normalize) - used by tailwind (https://tailwindcss.com/docs/preflight)
* Reboot (https://getbootstrap.com/docs/5.0/content/reboot/) - used by BS4+

**Comment by ruchernchong** [comment]
> There are a couple of alternatives that are actively maintained:
> 
> * Sanitize.css (https://github.com/csstools/sanitize.css)
> * Modern-normalize (https://github.com/sindresorhus/modern-normalize) - used by tailwind (https://tailwindcss.com/docs/preflight)
> * Reboot (https://getbootstrap.com/docs/5.0/content/reboot/) - used by BS4+

Which ones of those are more commonly used today?

**Comment by miquelfire** [comment]
When I redid my site recently, I went with modern normalize because I was trying to use Tailwind (I hated it, but I'm sure there's a good use case for it if you're not regenerating the CSS all the time)

**Comment by maurer2** [comment]
> > There are a couple of alternatives that are actively maintained:
> > 
> > * Sanitize.css (https://github.com/csstools/sanitize.css)
> > * Modern-normalize (https://github.com/sindresorhus/modern-normalize) - used by tailwind (https://tailwindcss.com/docs/preflight)
> > * Reboot (https://getbootstrap.com/docs/5.0/content/reboot/) - used by BS4+
> 
> Which ones of those are more commonly used today?

Hello, ***Reboot*** is probably by far the most downloaded one as it it is part of Bootstrap 4 and 5 which is still hugely popular.
***Modern-normalize*** seems to be becoming more widespread in part due to Tailwind becoming more popular. That package also seems to be much more actively maintained at the moment. 
  ***Sanitize.css*** seems to be the most popular standalone package, that people actually add as a dependency to their project.

I would probably use Sanitize.css or Modern-normalize in non-Bootstrap projects, use the built in Modern-normalize in Tailwind projects and use the already included Reboot when working on a modern Bootstrap projects (newer than 3).

Here is a graph of the download statistics (Reboot's popularity is probably misleading, as their is no official standalone package of it): https://www.npmtrends.com/bootstrap-vs-modern-normalize-vs-sanitize.css-vs-normalize.css  

Cheers

**Comment by ruchernchong** [comment]
> > > There are a couple of alternatives that are actively maintained:
> > > 
> > > * Sanitize.css (https://github.com/csstools/sanitize.css)
> > > * Modern-normalize (https://github.com/sindresorhus/modern-normalize) - used by tailwind (https://tailwindcss.com/docs/preflight)
> > > * Reboot (https://getbootstrap.com/docs/5.0/content/reboot/) - used by BS4+
> > 
> > 
> > Which ones of those are more commonly used today?
> 
> Hello, _**Reboot**_ is probably by far the most downloaded one as it it is part of Bootstrap 4 and 5 which is still hugely popular.
> _**Modern-normalize**_ seems to be becoming more widespread in part due to Tailwind becoming more popular. That package also seems to be much more actively maintained at the moment.
> _**Sanitize.css**_ seems to be the most popular standalone package, that people actually add as a dependency to their project.
> 
> I would probably use Sanitize.css or Modern-normalize in non-Bootstrap projects, use the built in Modern-normalize in Tailwind projects and use the already included Reboot when working on a modern Bootstrap projects (newer than 3).
> 
> Here is a graph of the download statistics (Reboot's popularity is probably misleading, as their is no official standalone package of it): https://www.npmtrends.com/bootstrap-vs-modern-normalize-vs-sanitize.css-vs-normalize.css
> 
> Cheers

Awesome! Thanks for the reply!

**Comment by wang1212** [comment]
Maybe take a look at this: 

> https://github.com/csstools/normalize.css#differences-from-necolasnormalizecss
