### ISSUE TITLE
I need an example

### ISSUE THREAD

**Issue by MarcusMors** [necolas/normalize.css#869]
I usually download the file and use it as a normal css file, but I want to use through the npm package you recently implemented and I don't know how to use it.

**Comment by miquelfire** [comment]
There's too little data to know how to give you a useful example.

If you're using NPM because you're using something like glup or grunt to build a CSS file, you would add normalize to the list of files to process. When I use it, I have a ```@include 'node_modules/.../normalize.css';``` at the beginning of my source CSS file because some setting I use would replace the include line with the code in the css. If your setup has a list of files to 'compile', you would add normalize.css to that list at the start of the list.

If you're using the file directly, then I guess in your html, you just point at the path in the node_modules folder to the file.
